// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Curry = require("rescript/lib/js/curry.js");
var Query = require("./Query.bs.js");
var Dotenv = require("dotenv");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var ClientConfig = require("./gql/ClientConfig.bs.js");

Dotenv.config();

var graphEndpoint = Belt_Option.getWithDefault(process.env.GRAPH_ENDPOINT, "https://thegraph.com/something/something/default");

var client = ClientConfig.createInstance(undefined, "https://api.thegraph.com/subgraphs/name/alejandro-larumbe/chainlink-matic-mainnet", undefined);

var _getAllFeeds = Curry._6(client.rescript_query, {
        query: Query.GetAllFeeds.query,
        Raw: Query.GetAllFeeds.Raw,
        parse: Query.GetAllFeeds.parse,
        serialize: Query.GetAllFeeds.serialize,
        serializeVariables: Query.GetAllFeeds.serializeVariables
      }, undefined, undefined, undefined, undefined, undefined).then(function (result) {
      if (result.TAG === /* Ok */0) {
        Belt_Array.map(result._0.data.feeds, (function (param) {
                var feedData = "number,timestamp,value";
                var finishedProcessing = false;
                while(!finishedProcessing) {
                  
                };
                Fs.writeFileSync("../rawData/" + param.name + ".csv", feedData, "utf8");
                
              }));
        return ;
      }
      console.log("Error (with GetAllFeeds): ", result._0);
      
    });

exports.graphEndpoint = graphEndpoint;
exports.client = client;
exports._getAllFeeds = _getAllFeeds;
/*  Not a pure module */
