// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ApolloClient__React_Hooks_UseMutation = require("reason-apollo-client/src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseMutation.bs.js");

var Raw = {};

var query = (require("@apollo/client").gql`
  mutation createUser($object: user_insert_input!)  {
    insert_user_one(object: $object)  {
      __typename
      ethAddress
      userName
    }
  }
`);

function parse(value) {
  var value$1 = value.insert_user_one;
  var tmp;
  if (value$1 == null) {
    tmp = undefined;
  } else {
    var value$2 = value$1.userName;
    tmp = {
      __typename: value$1.__typename,
      ethAddress: value$1.ethAddress,
      userName: !(value$2 == null) ? value$2 : undefined
    };
  }
  return {
          insert_user_one: tmp
        };
}

function serialize(value) {
  var value$1 = value.insert_user_one;
  var insert_user_one;
  if (value$1 !== undefined) {
    var value$2 = value$1.userName;
    var userName = value$2 !== undefined ? value$2 : null;
    var value$3 = value$1.ethAddress;
    var value$4 = value$1.__typename;
    insert_user_one = {
      __typename: value$4,
      ethAddress: value$3,
      userName: userName
    };
  } else {
    insert_user_one = null;
  }
  return {
          insert_user_one: insert_user_one
        };
}

function serializeInputObjectuser_insert_input(inp) {
  var a = inp.ethAddress;
  var a$1 = inp.userName;
  return {
          ethAddress: a !== undefined ? a : undefined,
          userName: a$1 !== undefined ? a$1 : undefined
        };
}

function serializeVariables(inp) {
  return {
          object: serializeInputObjectuser_insert_input(inp.object)
        };
}

function makeVariables(object_, param) {
  return {
          object: object_
        };
}

function makeInputObjectuser_insert_input(ethAddress, userName, param) {
  return {
          ethAddress: ethAddress,
          userName: userName
        };
}

var CreateUser_inner = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  serializeInputObjectuser_insert_input: serializeInputObjectuser_insert_input,
  makeVariables: makeVariables,
  makeInputObjectuser_insert_input: makeInputObjectuser_insert_input
};

var include = ApolloClient__React_Hooks_UseMutation.Extend({
      query: query,
      Raw: Raw,
      parse: parse,
      serialize: serialize,
      serializeVariables: serializeVariables
    });

var CreateUser_use = include.use;

var CreateUser_useWithVariables = include.useWithVariables;

var CreateUser = {
  CreateUser_inner: CreateUser_inner,
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  serializeInputObjectuser_insert_input: serializeInputObjectuser_insert_input,
  makeVariables: makeVariables,
  makeInputObjectuser_insert_input: makeInputObjectuser_insert_input,
  use: CreateUser_use,
  useWithVariables: CreateUser_useWithVariables
};

exports.CreateUser = CreateUser;
/* query Not a pure module */
